# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-10 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aroundme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_description', models.TextField()),
                ('continue_period', models.CharField(max_length=50)),
                ('event_occur_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='member',
            name='id',
        ),
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='member_id1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aroundme.Member'),
        ),
        migrations.AddField(
            model_name='event',
            name='member_id2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aroundme.Member'),
        ),
    ]
