# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-18 01:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aroundme', '0003_auto_20160910_0917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anniversary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('place', models.TextField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('datetime_start', models.DateTimeField()),
                ('datetime_finish', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='member_id1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='member_id2',
        ),
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.AddField(
            model_name='personalevent',
            name='member_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalevent_member_main', to='aroundme.Member'),
        ),
        migrations.AddField(
            model_name='personalevent',
            name='member_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personalevent_member_sub', to='aroundme.Member'),
        ),
        migrations.AddField(
            model_name='anniversary',
            name='member_main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversary_member_main', to='aroundme.Member'),
        ),
        migrations.AddField(
            model_name='anniversary',
            name='member_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anniversary_member_sub', to='aroundme.Member'),
        ),
    ]
